classNames:
- negative
- positive
columnNames:
- qid
- question_text
- target
- predictions
label: validation
labelColumnName: target
predictionScoresColumnName: predictions
textColumnName: question_text
